source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod "Dispatcher", "~> 0.1.2"
pod "Swalt", :path => "../"

target 'Swalt_Example', :exclusive => true do
end

target 'Swalt_Tests', :exclusive => true do
end
